### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by parsibox** [HusseinYoussef/Arabic-OCR#4]
hi
in install it say :
```
pip3 install -r requirements.txt
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: numpy in /home/mohsen/.local/lib/python3.6/site-packages (from -r requirements.txt (line 1)) (1.18.3)
Requirement already satisfied: opencv-python in /home/mohsen/.local/lib/python3.6/site-packages (from -r requirements.txt (line 2)) (4.2.0.34)
Requirement already satisfied: scikit-learn in /usr/lib64/python3.6/site-packages (from -r requirements.txt (line 3)) (0.22.2.post1)
Requirement already satisfied: scikit-image in /home/mohsen/.local/lib/python3.6/site-packages (from -r requirements.txt (line 4)) (0.16.2)
Requirement already satisfied: pandas in /home/mohsen/.local/lib/python3.6/site-packages (from -r requirements.txt (line 5)) (0.25.3)
Requirement already satisfied: matplotlib in /home/mohsen/.local/lib/python3.6/site-packages (from -r requirements.txt (line 6)) (3.2.1)
Collecting multiprocessing
  Using cached multiprocessing-2.6.2.1.tar.gz (108 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3.6 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-oe37fbft/multiprocessing/setup.py'"'"'; __file__='"'"'/tmp/pip-install-oe37fbft/multiprocessing/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-oe37fbft/multiprocessing/pip-egg-info
         cwd: /tmp/pip-install-oe37fbft/multiprocessing/
    Complete output (6 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-oe37fbft/multiprocessing/setup.py", line 94
        print 'Macros:'
                      ^
    SyntaxError: Missing parentheses in call to 'print'. Did you mean print('Macros:')?
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

```

**Comment by HusseinYoussef** [comment]
It seems that it somehow depends on the python version or something. I removed "multiprocessing" from requirements file. Try again and let me know.

**Comment by parsibox** [comment]
intall is now ok but it has no output and sometime have error

```
[mohsen@localhost src]$ python3.6 OCR.py 
  0%|                                                                                                                                                                                        | 0/1 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "OCR.py", line 115, in <module>
    running_time.append(run(images_path))
  File "OCR.py", line 63, in run
    img_name = image_path.split('\\')[1].split('.')[0]
IndexError: list index out of range

```

**Comment by HusseinYoussef** [comment]
Did you follow the directory structure instructions?
You must create a folder named "test" in the same folder with OCR.py, so the path should be src/test/{your images} and the output folder will be created next to "test" folder when done that contains the corresponding text inside it.

**Comment by HusseinYoussef** [comment]
Your images should be .png too but you can modify the code as you like.
